<!DOCTYPE html>
<html id="important">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link type="text/css" rel="stylesheet" href="/css/materialize.min.css"  media="screen,projection">
		<?php Css::add('helpers'); ?>
		<?=Css::inc()?>
	</head>
	<body class="max-width row">
		<?php View::content(); ?>
		<script src="/javascript/materialize.min.js"></script>
	</body>
</html>