<!DOCTYPE html>
<html id="important">
    <head>
        <link href="/css/material-icons.css" rel="stylesheet">
        <link href="/css/materialize.min.css" rel="stylesheet">
        <link href="/css/style.css" rel="stylesheet">
        <link href="/css/helpers.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>

    <body class="row">
        <h1 class="center-align mt10">KuBox <sup>v3</sup></h1>
        <h2 class="black white-text center-align mb5 pb10">Be box my friend</h2>
        <aside class="col s0 m0 l3">
            <?php View::partial('files'); ?>
        </aside>
        <main class="col s12 m12 l9">
            <h3>Boxes</h3>
            <?php View::content(); ?>
        </main>
        <script src="/javascript/materialize.min.js"></script>
    </body>
</html>