
<form method="post">
    <div>
        <label>Caja:</label>
        <div><?=$box->name?></div>
    </div>
    <div>
        <?php
        $variables = (new Variables)->readByCode($box->code);
        foreach ($variables as $k=>$v) : ?>
            <label><?=$k?>:</label>
            <input type="text" name="<?=$k?>" value="<?=_::v($box->variables, $k)?>">
        <?php endforeach; ?>
    </div>
    <div>
        <button class="btn orange darken-1" name="action" value="save_variables">SAVE</button>
	    <a class="btn blue darken-1" href="/admin/pages/?dir=<?=$box->dir?>&file=<?=$box->file?>">BACK</a>
    </div>
    <input type="hidden" name="pages_id" value="<?=$pages_id?>">
</form>
